### ISSUE TITLE
Installing Perl packages

### ISSUE THREAD

**Issue by sbguthery** [ibm-cloud-docs/cloud-shell#1]
Installing Perl packages in an IBM Cloud shell fails for lack of permissions on /usr/local.  Normally prefixing the cpan install with 'sudo' solves this but there is no 'sudo' available in the shell.

Thanks in advance for any suggestions?

Cheers, Scott

All tests successful.
Files=4, Tests=9,  1 wallclock secs ( 0.03 usr  0.04 sys +  0.15 cusr  0.10 csys =  0.32 CPU)
Result: PASS
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/make test -- OK
Running make install
Manifying 1 pod document
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/local/man/man3'
mkdir /usr/local/man/man3: Permission denied at /usr/share/perl/5.22/ExtUtils/Install.pm line 477.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
Makefile:718: recipe for target 'pure_site_install' failed
make: *** [pure_site_install] Error 13
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/make install  -- NOT OK

**Comment by christoc-ibm** [comment]
I checked with the dev team, who said that IBM Cloud Shell is a restricted shell and sudo is not permitted. This is stated in the FAQ: https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-faqs#faq-sudo

I hope this helps answer your question.
