### ISSUE TITLE
Command "ibmcloud cf push node-helloworld" failed

### ISSUE THREAD

**Issue by johnhaslam** [ibm-cloud-docs/cloud-shell#1]
From https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-getting-started, final step is

`ibmcloud cf push node-helloworld`

but this appears only to work if node-helloworld is unique across the wider environment. I had to add random characters to the name to get this to work.

**Comment by cjcarpen** [comment]
Hi @johnhaslam, thanks for opening this issue! Based on your feedback, we've updated the getting started tutorial to clarify that step: https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-getting-started#deploy-app
