### ISSUE TITLE
Adding more for troubleshooting doc

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/cloud-shell#11]
I'd like to update the content as below. You can see the detail in the internal KB https://watson.service-now.com/kb_view.do?sysparm_article=KB0014293 if you have access.

DOC URL: https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-troubleshooting

Why can't my sessions start?

What’s happening
When you try to start Cloud Shell or restart it after you were idle or your connection was lost, the following message is displayed:

`**Session could not be started. Please wait for a few minutes, then restart the cloud shell and try again.**`

How to fix it
1. Refresh your Cloud Shell browser tab or window. If Cloud Shell still can't start, try restarting from the Cloud Shell menu.
2. If Cloud Shell still can't start, check if the IP address restriction is defined for the account or the user. https://cloud.ibm.com/docs/account?topic=account-ips
3. if the IP address restriction is defined, add the Cloud Shell ingress IP ranges in order to log in from the Cloud Shell service. https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-cs-ip-ranges.
4. if the IP address restriction is not defined and you continue to see this issue, create a support case.

**Comment by tnakajo** [comment]
@christoc-ibm any updates?

**Comment by christoc-ibm** [comment]
@tnakajo - Thanks for providing additional content. It's now in production at this URL:
https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-troubleshooting
