### ISSUE TITLE
Incompatible with IBM TOTP - `Authorize Redirect ratelimit`

### ISSUE THREAD

**Issue by movinglightspeed** [ibm-cloud-docs/cloud-shell#2]
I am currently using IBM TOTP from https://cloud.ibm.com/user/login-settings

Time-based one-time passcode authentication

It uses IBM Verify for IBMid MFA. This is compatible and crashes IBM Cloud shell with endless redirecting.

[IBMCloudShellHAR2020-07-30-21-35-46.zip](https://github.com/ibm-cloud-docs/cloud-shell/files/5004739/IBMCloudShellHAR2020-07-30-21-35-46.zip)

Attached is HAR file. I've heard from support case that it will be supported in future release but creating issue here for tracking and documentation.

**Comment by christoc-ibm** [comment]
@movinglightspeed Apologies for the delayed response. The following doc confirms support of TOTP:
https://cloud.ibm.com/docs/account?topic=account-types
