### ISSUE TITLE
no docker on cloud shell

### ISSUE THREAD

**Issue by elzKit** [ibm-cloud-docs/cloud-shell#9]
There is no docker installed on cloud shell. What is the default tool that can be used in this env to build a docker container (in order to push it to ibm cloud registry)?
Sorry if the question is trivial.

**Comment by christoc-ibm** [comment]
@hartyt - This is an old issue, but can you please answer it? Thank you!

**Comment by hartyt** [comment]
Docker is correctly not supported, the good news is that it will be supported very soon hopefully later in Q2.
